### ISSUE TITLE
Linux builds do not run due to missing classes

### ISSUE THREAD

**Issue by Phantop** [catfoolyou/Eaglercraft-1.12-Desktop-Runtime#24]
As the title says, attempting run either the builds from Releases or building from source fails with the [attached log](https://github.com/catfoolyou/Eaglercraft-1.12-Desktop-Runtime/files/15253670/latest.log). Assuming everything is built/packaged correctly, I'm guessing something odd is happening with classpath on the launch script?

Also, running from sources ends with the following line, which I've seen before from native libs expecting to link against a specific Java version. It's not 17 (at least, not the version of OpenJDK 17 available in the Arch Linux repos), I can say that much, so if you know that it would be really helpful to throw into the documentation!

```
Inconsistency detected by ld.so: dl-lookup.c: 106: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by catfoolyou** [comment]
Well because I'm a dumbass and I don't know what exactly is the problem because I've never run into it, I can't directly help you with this. But a 5 second google search revealed [this](https://stackoverflow.com/questions/55847497/how-do-i-troubleshoot-inconsistency-detected-dl-lookup-c-111-java-result-12). Look into that. It's clearly some sort of library error in your JDK specific to your Linux distro. Try switching to OpenJDK 17 and see if that helps.

**Comment by Phantop** [comment]
Oh yeah, _I'm also_ a bit of a dumbass, heh. Thought to use Adoptium's OpenJDK 21 builds an Arch's OpenJDK 17 builds, but not Adoptium's 17. That fixed it.
